version: 2.1
executors:
  docker-executor:
    docker:
      - image: sjmiller609/helm-build:latest
jobs:
  release:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Helm package
          command: ./bin/build
      - run:
          name: Helm package
          command: ./bin/publish
workflows:
  version: 2.1
  helm-chart:
    jobs:
      - release:
          filters:
            branches:
              only: master
