apiVersion: v1
kind: Secret
metadata:
  name: dhcp-db-secret
data:
  host: {{ printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace | b64enc | quote }}
  user: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
