image:
  repository: sjmiller609
  name: kea-dhcp
  version: 0.0.6
  pullPolicy: IfNotPresent
pool: "192.168.2.10-192.168.2.254"
subnet: "192.168.2.0/24"
logLevel: "DEBUG"

postgresql:
  postgresqlUsername: postgres
  postgresqlPassword: defaultpostgrespassword
  servicePort: 5432
  service:
    type: ClusterIP
  initdbScripts:
    my_init_script.sql: |
      CREATE DATABASE kea;
      GRANT ALL PRIVILEGES ON DATABASE kea TO postgres
